### ISSUE TITLE
SourceMapping Problem

### ISSUE THREAD

**Issue by cspeer** [carrot/gulp-accord#3]
Hi,

basically I'm generating my sourcemaps exactly like in your example, except that I use `accord('minify-js')`:

```
var gulp = require('gulp'),
    sourcemaps = require('gulp-sourcemaps'),
    accord = require('gulp-accord');

gulp.task('default', function(){
  gulp.src('./test.styl')
  .pipe(sourcemaps.init())
  .pipe(accord('stylus'))
  .pipe(sourcemaps.write('.'))
  .pipe(gulp.dest('./out'))
});
```

So what happens is that `sourcemaps.write('.')` receives the minified version of the javascript file instead of the original and thus saves a minified version in the sourcemaps which kinda destroys its purpose.

Any ideas?

Thanks,
Chris

**Comment by jescalan** [comment]
Hey Chris,

Honestly, I'm not sure I understand your issue, I'm sorry! A source map is supposed to map back to the original version of a file, so I can't see why the minify js adapter would map to the minified version, unless it was already minified before being processed. With accord, all the source mapping is handled in one place, it's not unique across different languages, so it doesn't make sense to me that it work would with stylus but have completely different behavior with minify-js.

Maybe you could dig a little deeper?

**Comment by cspeer** [comment]
Yeah, sorry, a sourcemap along with the source mapping can hold the content of the original file in an attribute named `sourcesContent`. This is to easily map back to original source code without providing a separate javascript file that holds the original source code.
If I comment out the call to accord, this is is exactly what happens. But if accord is used the sourcemapper receives the minified version instead.

Hope this describes it better :)

**Comment by cspeer** [comment]
I thought I could simply reverse the order: Write the sourcemaps _before_ I minify the code, but if I do I get the following error:

```
/Users/cspeer/Development/htdocs/atameo/node_modules/when/lib/decorators/unhandledRejection.js:80
        throw e;
        ^
Error
    at new JS_Parse_Error (eval at <anonymous> (/Users/cspeer/Development/htdocs/atameo/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:1526:18)
    at js_error (eval at <anonymous> (/Users/cspeer/Development/htdocs/atameo/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:1534:11)
    at croak (eval at <anonymous> (/Users/cspeer/Development/htdocs/atameo/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2026:9)
    at token_error (eval at <anonymous> (/Users/cspeer/Development/htdocs/atameo/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2034:9)
    at unexpected (eval at <anonymous> (/Users/cspeer/Development/htdocs/atameo/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2040:9)
    at semicolon (eval at <anonymous> (/Users/cspeer/Development/htdocs/atameo/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2060:56)
```

**Comment by jescalan** [comment]
If you comment out the call to accord, the file isn't processed at all, right? So that doesn't really show anything...

**Comment by jescalan** [comment]
So the way I see it, either sourcemaps are completely broken in accord, or something really strange is happening here. If you run it with any other adapter that is not `minify-js`, does the sourcemap work as expected?

**Comment by cspeer** [comment]
Yes, I tried minify-css and it works as excpeted.
However, I wrote a simple test script:

```
gulp
  .task('accordmaps', function() {
    return gulp
      .src(['./client/javascripts/**/*.js'])
      .pipe(sourcemaps.init())
      .pipe(accord('minify-js'))
      .pipe(sourcemaps.write('./'))
      .pipe(gulp.dest(('./client/javascripts/test')))
    ;
  })
;
```

this produces for example the following source map http://pastebin.com/Asaw19eV
when it should have created something like this: http://pastebin.com/mv1SyCi4

The issue here is not that in the first file it holds minified code in `sourcesContent` but the content of a completely different file!! When I comment the call to accord however, the code in `sourcesContent` is correct.

**Comment by cspeer** [comment]
If I split it up in 2 tasks: first do the sourcemapping, then minify, everything is fine..

**Comment by jescalan** [comment]
The two different example sourcemaps you have in that last comment are for 2 entirely different files... it seems like something else is going on here outside of accord or gulp-accord. It might be the way that uglify-js reports the sources? I am not sure honestly.

**Comment by cspeer** [comment]
Yeah, thats what you would think because of the "sources" attribute... I
know. But rest assured, they are not!

**Comment by cspeer** [comment]
It's the outcome of the processing of the exact same source file, except
one time accord is involved and the other time it's not.

**Comment by jescalan** [comment]
When you comment out accord, the file is not processed in any way. So not really. One time nothing at all happens to the file, the other time accord processes it. You cannot make any comparisons here to what happens when accord is commented out, this is like saying "I ran my code and there was an error, but when I commented out all the code there was no error!" -- it just doesn't mean anything...

**Comment by cspeer** [comment]
Ok then... here you go https://github.com/cspeer/accordmaps
Please clone the project, take a look at `gulpfile.js`, then run `npm install` and finally run `gulp doit`.
Now have a look at the source map files in `output/`, especially `output/sub/two.js.map`. You can see that `sourcesContent` contains `["var one = 'file number 1';\n"]` when it should contain `["var two = 'file number 2';\n"]`, right?

**Comment by jescalan** [comment]
I can see that, and I do understand the issue now. It's a very strange one, has never come up before, and I just don't know what's causing it.

I suspect it is it might be an issue with uglifyjs, but I can't be sure. There is [a little hackery](https://github.com/jescalan/accord/blob/master/lib/adapters/minify-js/2.x.coffee#L26) in accord's adapter for uglifyjs in order to get sourcemaps to work correctly, and a few open issues in uglifyjs regarding sourcemaps.

If you'd like to take a stab at trying to correct these issues I'd be happy to advise where I can, but I currently don't have the time available to patch this entirely myself.

**Comment by cspeer** [comment]
Interesting is that if you don't use this recursive glob (*_/_.js), it works as expected with multiple files. So my guess would be that it's got something to do with that. But I'm afraid I don't have time to take a closer look at this right now either. The workaround (splitting sourcemapping and uglifiying into to separate tasks) works for now. Sorry.

**Comment by jescalan** [comment]
That is interesting, this means it's likely something to do with how gulp is passing through and handling the file paths.
